Repository munich-quantum-toolkit/syrec, pull requests merged in 2022-09, with the labels that each got.

#45 ✨ Foundation for Synthesis Methods
  include/algorithms/synthesis/dd_synthesis.hpp
  include/algorithms/synthesis/encoding.hpp
  include/core/io/pla_parser.hpp
  include/core/truthTable/truth_table.hpp
  src/CMakeLists.txt
  src/algorithms/synthesis/dd_synthesis.cpp
  src/algorithms/synthesis/encoding.cpp
  src/core/io/pla_parser.cpp
  src/core/truthTable/truth_table.cpp
  test/CMakeLists.txt
  test/circuits/BitwiseXor2Bit.pla
  test/circuits/CNOT.pla
  test/circuits/CUSTOMTT1.pla
  test/circuits/CUSTOMTT2.pla
  test/circuits/EXTENDTT.pla
  test/circuits/HUFF1.pla
  test/circuits/HUFF2.pla
  test/circuits/Ident2Bit.pla
  test/circuits/Max.pla
  test/circuits/SWAP.pla
  test/circuits/Toffoli.pla
  test/circuits/X2Bit.pla
  test/circuits/and.pla
  test/circuits/or.pla
  test/unittests/test_extend_tt.cpp
  test/unittests/test_huffman.cpp
  test/unittests/test_pla_parser.cpp
  test/unittests/test_tt_to_dd.cpp
Labels: enhancement

#68 🐛 Fix Editable Installs
  pyproject.toml
  setup.py
Labels: bug

#70 ✨ Add pre-commit configuration
  .clang-format
  .cmake-format.yaml
  .flake8
  .github/codecov.yml
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  MANIFEST.in
  README.md
  include/core/circuit.hpp
  include/core/syrec/expression.hpp
  include/core/syrec/module.hpp
  include/core/syrec/statement.hpp
  mqt/syrec/__init__.py
  mqt/syrec/syrec_editor.py
  noxfile.py
  pyproject.toml
  setup.py
  src/CMakeLists.txt
  src/core/io/pla_parser.cpp
  src/core/syrec/parser.cpp
  test/CMakeLists.txt
  test/circuits/alu_2.src
  test/circuits/circuits_simulation.json
  test/circuits/circuits_simulation_add_lines.json
  test/circuits/circuits_synthesis.json
  test/circuits/circuits_synthesis_add_lines.json
  test/circuits/for_32.src
  test/circuits/gray_binary_conversion_16.src
  test/circuits/parity_4.src
  test/circuits/parity_check_16.src
  test/python/test_syrec.py
Labels: enhancement, dependencies

#72 🔧 Proper Versioning in Deploy CI
  .github/workflows/deploy.yml
Labels: bug

#74 📝 Initialize Documentation on ReadTheDocs
  .readthedocs.yaml
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  docs/source/refs.bib
  noxfile.py
  setup.py
Labels: documentation

#76 🔧 Add in-progress cancellation to CI workflows
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
Labels: continuous integration, usability

#75 🔧 Update CodeQL configuration
  .github/codeql-config.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .lgtm.yml
  include/core/syrec/grammar.hpp
  include/core/syrec/module.hpp
  include/core/syrec/statement.hpp
  noxfile.py
  setup.py
  src/core/syrec/parser.cpp
  test/CMakeLists.txt
  test/configs/circuits_simulation.json
  test/configs/circuits_simulation_add_lines.json
  test/configs/circuits_synthesis.json
  test/configs/circuits_synthesis_add_lines.json
  test/python/test_syrec.py
  test/unittests/test_add_lines_simulation.cpp
  test/unittests/test_add_lines_synthesis.cpp
  test/unittests/test_simulation.cpp
  test/unittests/test_synthesis.cpp
Labels: github_actions, continuous integration
