Repository munich-quantum-toolkit/syrec, pull requests merged in 2025-08, with the labels that each got.

#347 🐛 Fix of variable qubits lookup during synthesis of VariableAccess in recursive/repeated Call-/UncallStatements
  docs/source/SyrecLanguageSemantics.rst
  include/algorithms/synthesis/first_variable_qubit_offset_lookup.hpp
  include/algorithms/synthesis/syrec_synthesis.hpp
  include/core/syrec/variable.hpp
  src/CMakeLists.txt
  src/algorithms/synthesis/first_variable_qubit_offset_lookup.cpp
  src/algorithms/synthesis/syrec_synthesis.cpp
  src/core/annotatable_quantum_computation.cpp
  src/core/syrec/variable.cpp
  src/mqt/syrec/syrec_editor.py
  test/unittests/simulation/data/test_synthesis_of_basic_operations.json
  test/unittests/simulation/test_synthesis_basic_operations.cpp
  test/unittests/test_first_variable_qubit_offset_lookup.cpp
Labels: c++, fix

#351 Further synthesis tests using simulation for verification
  test/CMakeLists.txt
  test/unittests/simulation/data/test_sim_production_assignStatement.json
  test/unittests/simulation/data/test_sim_production_binaryExpression.json
  test/unittests/simulation/data/test_sim_production_callStatement.json
  test/unittests/simulation/data/test_sim_production_forStatement.json
  test/unittests/simulation/data/test_sim_production_ifStatement.json
  test/unittests/simulation/data/test_sim_production_shiftExpression.json
  test/unittests/simulation/data/test_sim_production_skipStatement.json
  test/unittests/simulation/data/test_sim_production_swapStatement.json
  test/unittests/simulation/data/test_sim_production_unaryExpression.json
  test/unittests/simulation/data/test_sim_production_unaryStatement.json
  test/unittests/simulation/data/test_sim_production_uncallStatement.json
  test/unittests/simulation/data/test_sim_production_variableExpression.json
  test/unittests/simulation/data/test_synthesis_of_basic_operations.json
  test/unittests/simulation/data/test_synthesis_settings_features.json
  test/unittests/simulation/fixtures/base_simulation_test_fixture.hpp
  test/unittests/simulation/fixtures/success/test_sim_production_assignStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_binaryExpression.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_callStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_forStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_ifStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_shiftExpression.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_skipStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_swapStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_unaryExpression.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_unaryStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_uncallStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_variableExpression.cpp
  test/unittests/simulation/fixtures/test_synthesis_settings_features.cpp
  test/unittests/simulation/fixtures/test_synthesized_full_circuit_simulation.cpp
  test/unittests/simulation/test_synthesis_basic_operations.cpp
Labels: c++

#352 ❤️ Add support option
  .github/CONTRIBUTING.md
  .github/SUPPORT.md
  .github/contributing.rst
  .github/support.rst
  .github/workflows/cd.yml
  .readthedocs.yaml
  README.md
  docs/DevelopmentGuide.rst
  docs/_static/build.svg
  docs/_static/costAwareAdder.svg
  docs/_static/custom.css
  docs/_static/guiAdder.png
  docs/_static/lineAwareAdder.svg
  docs/_static/mqt_dark.png
  docs/_static/mqt_light.png
  docs/_static/sim.png
  docs/_static/stat.svg
  docs/_templates/page.html
  docs/conf.py
  docs/contributing.md
  docs/description_and_features.md
  docs/index.md
  docs/installation.rst
  docs/library/AnnotatableQuantumComputation.rst
  docs/library/Library.rst
  docs/library/NBitValuesContainer.rst
  docs/library/Parser.rst
  docs/library/QubitInliningInformation.rst
  docs/library/Settings.rst
  docs/library/Simulation.rst
  docs/library/Synthesis.rst
  docs/references.md
  docs/refs.bib
  docs/source/Contributing.rst
  docs/source/DescriptionAndFeatures.rst
  docs/source/Publications.rst
  docs/source/Support.rst
  docs/source/SyrecLanguageSemantics.rst
  docs/source/index.rst
  docs/source/refs.bib
  docs/support.md
  docs/syrec_language_semantics.md
  noxfile.py
  pyproject.toml
  uv.lock
Labels: documentation
