Repository munich-quantum-toolkit/syrec, pull requests merged in 2025-09, with the labels that each got.

#362 👷📝 Set up templating
  .github/workflows/templating.yml
  README.md
  docs/conf.py
  docs/description_and_features.md
  docs/index.md
  docs/references.md
Labels: documentation, continuous integration

#368 🎨 Fix things forgotten in #317
  .readthedocs.yaml
  docs/refs.bib
  noxfile.py
Labels: documentation, dependencies, fix

#371 📝 Fix rendering of documentation
  docs/conf.py
Labels: documentation, fix

#374 👷 Add C++ coverage job
  .github/workflows/ci.yml
Labels: continuous integration, c++

#369 ✨Support for non-compile time constant expression indices in dimension access component of variable access
  docs/syrec_language_semantics.md
  include/algorithms/synthesis/syrec_cost_aware_synthesis.hpp
  include/algorithms/synthesis/syrec_line_aware_synthesis.hpp
  include/algorithms/synthesis/syrec_synthesis.hpp
  include/core/annotatable_quantum_computation.hpp
  include/core/syrec/parser/utils/custom_error_messages.hpp
  src/algorithms/synthesis/syrec_cost_aware_synthesis.cpp
  src/algorithms/synthesis/syrec_line_aware_synthesis.cpp
  src/algorithms/synthesis/syrec_synthesis.cpp
  src/core/annotatable_quantum_computation.cpp
  src/core/syrec/parser/components/custom_module_visitor.cpp
  test/unittests/simulation/data/test_sim_production_assignStatement.json
  test/unittests/simulation/data/test_sim_production_binaryExpression.json
  test/unittests/simulation/data/test_sim_production_forStatement.json
  test/unittests/simulation/data/test_sim_production_ifStatement.json
  test/unittests/simulation/data/test_sim_production_shiftExpression.json
  test/unittests/simulation/data/test_sim_production_swapStatement.json
  test/unittests/simulation/data/test_sim_production_unaryStatement.json
  test/unittests/simulation/data/test_sim_production_variableExpression.json
  test/unittests/simulation/fixtures/base_simulation_test_fixture.hpp
  test/unittests/simulation/fixtures/success/test_sim_production_assignStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_binaryExpression.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_ifStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_shiftExpression.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_swapStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_unaryStatement.cpp
  test/unittests/simulation/fixtures/success/test_sim_production_variableExpression.cpp
  test/unittests/syrec/parser/data/error/test_production_parameter_errors.cpp
  test/unittests/test_annotated_quantum_computation.cpp
  test/unittests/test_synthesis_qubit_inlining_information.cpp
Labels: feature, c++
